#!/usr/bin/env bash

# Rofi cheatsheet - fuzzy searchable shortcuts reference
# Usage: cheatsheet.sh

# Helper to format entries with pango markup
# Category = bold, Shortcut = bold, Description = dimmed
entry() {
    local cat="$1" key="$2" desc="$3"
    printf '<b>%-12s</b>  <b>%-22s</b>  <span alpha="60%%">%s</span>\n' "$cat" "$key" "$desc"
}

{
# ── Hyprland ──
entry "[Hyprland]" "SUPER+Return"        "Open terminal (kitty)"
entry "[Hyprland]" "SUPER+D"             "App launcher (rofi)"
entry "[Hyprland]" "SUPER+Q Q"           "Kill active window"
entry "[Hyprland]" "SUPER+F"             "Toggle fullscreen"
entry "[Hyprland]" "SUPER+L"             "Lock screen (hyprlock)"
entry "[Hyprland]" "SUPER+N"             "Toggle notifications"
entry "[Hyprland]" "SUPER+Y"             "Clipboard history"
entry "[Hyprland]" "SUPER+T"             "Tmux manager"
entry "[Hyprland]" "SUPER+?"             "Cheatsheet (this)"
entry "[Hyprland]" "SUPER+R"             "Resize mode (1-5, arrows)"
entry "[Hyprland]" "SUPER+SHIFT+Space"   "Toggle floating"
entry "[Hyprland]" "SUPER+C"             "Center floating window"
entry "[Hyprland]" "SUPER+SHIFT+P"       "Pin to all workspaces"
entry "[Hyprland]" "SUPER+G"             "Toggle window group"
entry "[Hyprland]" "SUPER+SHIFT+G"       "Lock active group"
entry "[Hyprland]" "SUPER+Tab"           "Next tab in group"
entry "[Hyprland]" "SUPER+SHIFT+Tab"     "Previous tab in group"
entry "[Hyprland]" "ALT+Tab"             "Cycle windows"
entry "[Hyprland]" "SUPER+I"             "Image viewer (imv)"
entry "[Hyprland]" "SUPER+SHIFT+T"       "Theme switcher"
entry "[Hyprland]" "SUPER+SHIFT+F"       "Focus mode toggle"
entry "[Hyprland]" "SUPER+E"             "File manager (thunar)"
entry "[Hyprland]" "SUPER+\`"            "Scratchpad terminal"
entry "[Hyprland]" "SUPER+Z"             "Zoom toggle"
entry "[Hyprland]" "SUPER+S"             "Special workspace"
entry "[Hyprland]" "Print"               "Screenshot (area)"
entry "[Hyprland]" "SUPER+B"             "btop (system monitor)"
entry "[Hyprland]" "SUPER+SHIFT+B"       "lazydocker"
entry "[Hyprland]" "SUPER+A"             "pavucontrol (audio)"
entry "[Hyprland]" "SUPER+SHIFT+E"       "Power menu"
entry "[Hyprland]" "SUPER+SHIFT+R"       "Reload Hyprland"
entry "[Hyprland]" "SUPER+Arrows"        "Move focus"
entry "[Hyprland]" "SUPER+SHIFT+Arrows"  "Move window"
entry "[Hyprland]" "SUPER+1-0"           "Switch workspace 1-10"
entry "[Hyprland]" "SUPER+SHIFT+1-0"     "Move to workspace"

# ── Tmux ──
entry "[Tmux]"     "Ctrl+f"              "Tmux sessionizer (fzf)"
entry "[Tmux]"     "Ctrl+a"              "Prefix key"
entry "[Tmux]"     "Ctrl+a ["            "Enter copy mode"
entry "[Tmux]"     "v  (copy mode)"      "Start visual selection"
entry "[Tmux]"     "y  (copy mode)"      "Copy to clipboard"
entry "[Tmux]"     "r  (copy mode)"      "Rectangle selection"
entry "[Tmux]"     "Ctrl+a p"            "Paste from clipboard"
entry "[Tmux]"     "C-n / C-p"           "Next / prev window"
entry "[Tmux]"     "Ctrl+a X"            "Quit tmux session"

# ── Neovim ──
entry "[Neovim]"   "Space ff"            "Find files (telescope)"
entry "[Neovim]"   "Space fg"            "Live grep (telescope)"
entry "[Neovim]"   "Space fh"            "Search keymaps"
entry "[Neovim]"   "Space fb"            "Search buffers"
entry "[Neovim]"   "Space ."             "File tree"
entry "[Neovim]"   "gd"                  "Hover documentation"
entry "[Neovim]"   "gD"                  "Go to definition"
entry "[Neovim]"   "Space ca"            "Code action"
entry "[Neovim]"   "Space rn"            "Rename symbol"
entry "[Neovim]"   "Space q"             "Diagnostics list"
entry "[Neovim]"   "Space gr"            "Find references"
entry "[Neovim]"   "F5"                  "Debug start/continue"
entry "[Neovim]"   "F3"                  "Debug stop"
entry "[Neovim]"   "Space b"             "Toggle breakpoint"
entry "[Neovim]"   "Space ct"            "Copilot chat"
entry "[Neovim]"   "Space cq"            "Quick chat"
entry "[Neovim]"   "Ctrl+s"              "Save file"
entry "[Neovim]"   "K / J (visual)"      "Move lines up/down"
entry "[Neovim]"   "Space Y"             "Copy file to clipboard"
entry "[Neovim]"   "Space cp"            "Copy file path"
entry "[Neovim]"   "Space bb"            "Pick buffer"
entry "[Neovim]"   "Space bc"            "Close buffer"

# ── Shell ──
entry "[Shell]"    "nixswitch"           "Apply Nix configuration"
entry "[Shell]"    "nixup"               "Update flake + rebuild"
entry "[Shell]"    "nixtest"             "Test config (no build)"
entry "[Shell]"    "nixclean"            "Clean old generations"
entry "[Shell]"    "nixgen"              "List generations"
entry "[Shell]"    "nixsearch <pkg>"     "Search packages"
entry "[Shell]"    "nixvalidate"         "Pre-flight checks"
entry "[Shell]"    "nixinfo"             "Nix system status"
entry "[Shell]"    "checkport <port>"    "Check port usage"
entry "[Shell]"    "killport <port>"     "Kill process on port"
entry "[Shell]"    "serve [port]"        "HTTP server (def: 8000)"
entry "[Shell]"    "json [file]"         "Pretty print JSON"
entry "[Shell]"    "copy [file]"         "Copy to clipboard"
entry "[Shell]"    "paste [file]"        "Paste from clipboard"
entry "[Shell]"    "copypath"            "Copy directory path"
entry "[Shell]"    "cb / clipshow"       "Show clipboard info"
entry "[Shell]"    "cbw / clipwatch"     "Watch clipboard changes"
entry "[Shell]"    "cbc / clipclear"     "Clear clipboard"
entry "[Shell]"    "myip"                "Public IP address"
entry "[Shell]"    "localip"             "Local IP address"
entry "[Shell]"    "netinfo"             "Network information"
entry "[Shell]"    "speedtest"           "Internet speed test"

# ── Keys ──
entry "[Keys]"     "Alt+c"              "Show clipboard"
entry "[Keys]"     "Alt+v"              "Paste from clipboard"
entry "[Keys]"     "Alt+x"              "Clear clipboard"
entry "[Keys]"     "dev"                "Jump to ~/Dev"
entry "[Keys]"     "dots"               "Jump to ~/.dotfiles"
entry "[Keys]"     "cdtemp"             "Go to temp directory"
entry "[Keys]"     "cpwd"               "Copy current dir path"
entry "[Keys]"     "ccat <file>"        "Copy file to clipboard"
} | rofi -dmenu -i -markup-rows -theme ~/.config/rofi/cheatsheet.rasi > /dev/null 2>&1
