{config, lib, system, pkgs, vars, host, ... }:

let
  colors = import ../theme/colors.nix;
in
{

	environment = {
		variables = {
			XDG_CURRENT_DESKTOP="Hyprland";
			XDG_SESSION_TYPE="wayland";
			XDG_SESSION_DESKTOP="Hyprland";
		};

		sessionVariables = {
			QT_QPA_PLATFORM = "wayland";
			QT_WAYLAND_DISABLE_WINDOWDECORATION = "1";
			GDK_BACKEND = "wayland";
			QT_WAYLAND_FORCE_DPI="physicail";
			WLR_NO_HARDWARE_CURSORS = "1";
			MOZ_ENABLE_WAYLAND = "1";
			KITTY_ENABLE_WAYLAND="1";
			SDL_VIDEODRIVER="wayland";

		};

		systemPackages = with pkgs; [
			grimblast       	# Screenshot
			swayidle        	# Idle Daemon
			swaylock-effects        # Lock Screen
			wl-clipboard    	# Clipboard
			wlr-randr       	# Monitor Settings
			hyprland-autoname-workspaces
			networkmanagerapplet
			cliphist
			swww			# Wallpaper daemon
			insync			# Gdrive integration
			xfce.thunar		# File explorer GUI
			xfce.thunar-volman	# Auto manage removable drives etc..

			# Should be moved to own files
			swaynotificationcenter #loaded in seperate nix file
			libnotify

			#Other
			font-manager
			#obsidian

		];

	};
	security.pam.services.swaylock = {
		text = ''
			auth include login
			'';
	};

	programs = {
		hyprland = {                            # Window Manager
			enable = true;
			#package = hyprland.packages.${pkgs.system}.hyprland;
			#nvidiaPatches = true;
			xwayland.enable = true;
		};
	};
	systemd.sleep.extraConfig = ''
		AllowSuspend=no
		AllowHibernation=no
		AllowSuspendThenHibernate=no
		AllowHybridSleep=yes
		'';

	home-manager.users.${vars.user} =
	let
	execute =''
	exec-once=${pkgs.swayidle}/bin/swayidle -w timeout 600 '~/Scripts/swaylock.sh'
	'';
	in
	let
		hyprlandConf = with colors.scheme.default.hex;
		''
		autogenerated = 0

		monitor=,preferred,auto,auto

		env = XCURSOR_SIZE,24

		# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
		input {
			kb_layout = dk
				kb_variant =
				kb_model =
				kb_options =
				kb_rules =

				follow_mouse = 1

				touchpad {
					natural_scroll = no
				}

			sensitivity = -0.8 # -1.0 - 1.0, 0 means no modification.
		}

		general {
		# See https://wiki.hyprland.org/Configuring/Variables/ for more

			gaps_in = 5
				gaps_out = 20
				border_size = 2
				col.active_border = rgba(33ccffee) rgba(00ff99ee) 45deg
				col.inactive_border = rgba(595959aa)

				layout = dwindle

		# Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
				allow_tearing = false
		}

		decoration {
		# See https://wiki.hyprland.org/Configuring/Variables/ for more

			rounding = 10

				blur {
					enabled = true
					size = 8
					passes = 1
				}

            #drop_shadow = yes
            #	shadow_range = 4
            #	shadow_render_power = 3
            #	col.shadow = rgba(1a1a1aee)
		}

		animations {
			enabled = yes

		# Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

				bezier = myBezier, 0.05, 0.9, 0.1, 1.05

				animation = windows, 1, 7, myBezier
				animation = windowsOut, 1, 7, default, popin 80%
				animation = border, 1, 10, default
				animation = borderangle, 1, 8, default
				animation = fade, 1, 7, default
				animation = workspaces, 1, 6, default
		}

		dwindle {
		# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
			pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
				preserve_split = yes # you probably want this
		}

		gestures {
		# See https://wiki.hyprland.org/Configuring/Variables/ for more
			workspace_swipe = off
		}

		misc {
		# See https://wiki.hyprland.org/Configuring/Variables/ for more
			force_default_wallpaper = -1 # Set to 0 to disable the anime mascot wallpapers
			#no_vfr=false
			vrr = 1
			disable_hyprland_logo=true
			disable_splash_rendering=true
			mouse_move_enables_dpms=true
			key_press_enables_dpms=true
			background_color=0x111111
		}

		# Example per-device config
		# See https://wiki.hyprland.org/Configuring/Keywords/#executing for more
		# device:epic-mouse-v1 {
	 #       		sensitivity = -0.5
  #      		}

		# Example windowrule v1
		# windowrule = float, ^(kitty)$
		# Example windowrule v2
		# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
		# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more


		# See https://wiki.hyprland.org/Configuring/Keywords/ for more
		$mainMod = SUPER

		# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
		bind = $mainMod, Return, exec, kitty
		bind = $mainMod, Q, killactive,
		# bind = $mainMod, M, exit,
		#bind = $mainMod, E, exec, dolphin
		bind = SUPERSHIFT, SPACE, togglefloating,
		bind = $mainMod, D, exec, pkill rofi || rofi -show drun -theme ~/.config/rofi/launcher.rasi
		bind = $mainMod, P, pseudo, # dwindle
		bind = $mainMod, J, togglesplit, # dwindle
		bind=SUPERSHIFT,R,exec,${pkgs.hyprland}/bin/hyprctl reload
     		bind=SUPER,F,fullscreen,
		bind=SUPER,L,exec,~/Scripts/swaylock.sh
		bind=SUPER,N,exec,${pkgs.swaynotificationcenter}/bin/swaync-client -t
		bind = SUPERSHIFT, E,exec, pkill rofi || .config/rofi/powermenu.sh
        	bind=,print,exec,${pkgs.grimblast}/bin/grimblast --notify --freeze --wait 1 copysave area ~/Pictures/$(date +%Y-%m-%dT%H%M%S).png
		bind=SUPER,Y,exec,pkill rofi || cliphist list | rofi -dmenu -theme $HOME/.config/rofi/clipboard.rasi | cliphist decode | wl-copy
		bind=SUPER,code:49,exec,pypr toggle term
		bind=SUPER,Z,exec, pypr zoom
		bind=SUPER,E,exec,pypr toggle files

        	bind=,XF86AudioLowerVolume,exec,pactl set-sink-volume @DEFAULT_SINK@ -10%
        	bind=,XF86AudioRaiseVolume,exec,pactl set-sink-volume @DEFAULT_SINK@ +5%
         	bind=,XF86AudioMute,exec,pactl set-sink-mute @DEFAULT_SINK@ toggle

        	bind=,XF86AudioMicMute,exec, pactl set-source-mute @DEFAULT_SOURCE@ 1

		# Move focus with mainMod + arrow keys
		bind = $mainMod, left, movefocus, l
		bind = $mainMod, right, movefocus, r
		bind = $mainMod, up, movefocus, u
		bind = $mainMod, down, movefocus, d

		# Move active window + arrowkeys
		bind = SUPERSHIFT,left,movewindow, l
		bind = SUPERSHIFT,right,movewindow, r
		bind = SUPERSHIFT,up,movewindow, u
		bind = SUPERSHIFT,down,movewindow, d

		# Switch workspaces with mainMod + [0-9]
		bind = $mainMod, 1, workspace, 1
		bind = $mainMod, 2, workspace, 2
		bind = $mainMod, 3, workspace, 3
		bind = $mainMod, 4, workspace, 4
		bind = $mainMod, 5, workspace, 5
		bind = $mainMod, 6, workspace, 6
		bind = $mainMod, 7, workspace, 7
		bind = $mainMod, 8, workspace, 8
		bind = $mainMod, 9, workspace, 9
		bind = $mainMod, 0, workspace, 10

		# Move active window to a workspace with mainMod + SHIFT + [0-9]
		bind = $mainMod SHIFT, 1, movetoworkspace, 1
		bind = $mainMod SHIFT, 2, movetoworkspace, 2
		bind = $mainMod SHIFT, 3, movetoworkspace, 3
		bind = $mainMod SHIFT, 4, movetoworkspace, 4
		bind = $mainMod SHIFT, 5, movetoworkspace, 5
		bind = $mainMod SHIFT, 6, movetoworkspace, 6
		bind = $mainMod SHIFT, 7, movetoworkspace, 7
		bind = $mainMod SHIFT, 8, movetoworkspace, 8
		bind = $mainMod SHIFT, 9, movetoworkspace, 9
		bind = $mainMod SHIFT, 0, movetoworkspace, 10

		# Example special workspace (scratchpad)
		bind = $mainMod, S, togglespecialworkspace, magic
		bind = $mainMod SHIFT, S, movetoworkspace, special:magic

		# Scroll through existing workspaces with mainMod + scroll
		bind = $mainMod, mouse_down, workspace, e+1
		bind = $mainMod, mouse_up, workspace, e-1

		# Move/resize windows with mainMod + LMB/RMB and dragging
		bindm = $mainMod, mouse:272, movewindow
		bindm = $mainMod, mouse:273, resizewindow

		bind = SUPER,R,submap,resize
		submap=resize
		binde =,right,resizeactive,20 0
		binde =,left,resizeactive,-20 0
		binde =,up,resizeactive,0 -20
		binde =,down,resizeactive,0 20
		bind=,escape,submap,reset
		submap=reset

        #Steam
        windowrule=float,title:^(Steam)$
        windowrule=float,title:^(Friends List)$

		windowrulev2 = float,title:^(Insync)(.*)$
		$scratchpad = class:^(scratchpad)$
       		windowrulev2 = float,$scratchpad
       		windowrulev2 = workspace special silent,$scratchpad
       		windowrulev2 = center,$scratchpad

		$pavucontrol = class:^(pavucontrol)$
       		windowrulev2 = float,$pavucontrol
       		windowrulev2 = size 50% 40%,$pavucontrol
       		windowrulev2 = move 50% 6%,$pavucontrol
       		windowrulev2 = workspace special silent,$pavucontrol
       		windowrulev2 = opacity 0.80,$pavucontrol

		$thunar = class:^(thunar)$
		windowrulev2 = float,$thunar
		#windowrulev2 = size 60% 60%,$thunar
		#windowrulev2 = move 50% 6%,$thunar
		#windowrulev2 = workspace special silent,$thunar
		windowrulev2 = opacity 0.90,$thunar

		windowrulev2 = opacity 0.9 0.9,class:^(Slack|WebCord|Spotify|Kitty)$

		exec-once=${pkgs.swww}/bin/swww init
		exec-once=${pkgs.waybar}/bin/waybar
		exec-once=${pkgs.swaynotificationcenter}/bin/swaync
		exec-once=${pkgs.openrazer-daemon}/bin/openrazer-daemon
		exec-once=${pkgs.networkmanagerapplet}/bin/nm-applet --indicator
		exec-once=${pkgs.hyprland-autoname-workspaces}/bin/hyprland-autoname-workspaces
		exec-once=pypr
		exec-once = wl-clipboard-history -t
		exec-once = wl-paste --watch cliphist store
		exec-once = rm "$HOME/.cache/cliphist/db"   #it'll delete history at every restart
		exec-once = sleep 2 && ~/Scripts/swww_random.sh ~/Pictures/Wallpapers/
		exec-once = sleep 3 && insync start --qt-qpa-platform=xcb --no-daemon
		${execute}
		'';
	in
	{
		xdg.configFile."hypr/hyprland.conf".text = hyprlandConf;

	};
}
