user: 174
group: 244
permission:
  read: 109
  write: 163
  exec: 208
  exec-sticky: 200
  no-access: 239
  octal: 101
  acl: 117
  context: 172
date:
  hour-old: 140
  day-old: 142
  older: 243
size:
  none: 245
  small: 111
  medium: 178
  large: 95
inode:
  valid: 201
  invalid: 241
links:
  valid: 201
  invalid: 241
tree-edge: 241
git-status:
  default: 241
  unmodified: 241
  ignored: 241
  new-in-index: 200
  new-in-workdir: 200
  typechange: 111
  deleted: 95
  renamed: 200
  modified: 111
  conflicted: 95

