{config, lib, system, pkgs, vars, host, ... }:

let
  colors = import ../../theme/colors.nix;
in
{

	environment = {
		variables = {
			XDG_CURRENT_DESKTOP="Hyprland";
			XDG_SESSION_TYPE="wayland";
			XDG_SESSION_DESKTOP="Hyprland";
		};

		sessionVariables = {
			QT_QPA_PLATFORM = "wayland";
			QT_WAYLAND_DISABLE_WINDOWDECORATION = "1";
			GDK_BACKEND = "wayland";
			QT_WAYLAND_FORCE_DPI="physical";
			WLR_NO_HARDWARE_CURSORS = "1";
			MOZ_ENABLE_WAYLAND = "1";
			KITTY_ENABLE_WAYLAND="1";
			SDL_VIDEODRIVER="wayland";

		};

		systemPackages = with pkgs; [
			grimblast       	# Screenshot
			swayidle        	# Idle Daemon
			swaylock-effects        # Lock Screen
			wl-clipboard    	# Clipboard
			wlr-randr       	# Monitor Settings
			hyprland-autoname-workspaces
			networkmanagerapplet
			cliphist
			swww			# Wallpaper daemon
			insync			# Gdrive integration
			thunar			# File explorer GUI
			thunar-volman		# Auto manage removable drives etc..
			imv			# Simple image viewer

			# Should be moved to own files
			swaynotificationcenter #loaded in seperate nix file
			libnotify

			#Other
			font-manager
			#obsidian
			playerctl		# Media playback control
			brightnessctl		# Brightness control

		];

	};
	security.pam.services.swaylock = {
		text = ''
			auth include login
			'';
	};

	programs = {
		hyprland = {                            # Window Manager
			enable = true;
			withUWSM = true;
			#package = hyprland.packages.${pkgs.system}.hyprland;
			#nvidiaPatches = true;
			xwayland.enable = true;
		};
	};
	systemd.sleep.extraConfig = ''
		AllowSuspend=no
		AllowHibernation=no
		AllowSuspendThenHibernate=no
		AllowHybridSleep=yes
		'';

	home-manager.users.${vars.user} =
	let
	execute =''
	exec-once=${pkgs.swayidle}/bin/swayidle -w timeout 600 '~/Scripts/swaylock.sh'
	'';
	in
	let
		hyprlandConf = with colors.scheme.default.hex;
		''
		autogenerated = 0

		monitor=,preferred,auto,auto

		env = XCURSOR_SIZE,24
		env = XCURSOR_THEME,Adwaita

		# For all categories, see https://wiki.hyprland.org/Configuring/Variables/
		input {
			kb_layout = dk
				kb_variant =
				kb_model =
				kb_options =
				kb_rules =

				follow_mouse = 1

				touchpad {
					natural_scroll = no
				}

			sensitivity = 0.0 # -1.0 - 1.0, 0 means no modification.
		}

		general {
		# See https://wiki.hyprland.org/Configuring/Variables/ for more

			gaps_in = 5
				gaps_out = 20
				border_size = 2
				col.active_border = rgba(${cyan}ee) rgba(${green}ee) 45deg
				col.inactive_border = rgba(${gray}aa)

				layout = dwindle

		# Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
				allow_tearing = false
		}

		group {
			col.border_active = rgba(${cyan}ee)
			col.border_inactive = rgba(${gray}aa)

			groupbar {
				enabled = true
				font_size = 14
				height = 30
				render_titles = true
				col.active = rgb(${blue})
				col.inactive = rgb(${gray})
				text_color = rgb(ffffff)
				rounding = 6
				gaps_in = 3
				gaps_out = 3
			}
		}

		decoration {
		# See https://wiki.hyprland.org/Configuring/Variables/ for more

			rounding = 10
			dim_inactive = true
			dim_strength = 0.15

				blur {
					enabled = true
					size = 8
					passes = 2
					vibrancy = 0.1696
				}

				shadow {
					enabled = true
					range = 15
					render_power = 2
					color = rgba(1a1a1aee)
				}

		}

		render {
			# Experimental: can improve FPS on underpowered devices
			# new_render_scheduling = true
		}

		animations {
			enabled = yes

		# Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more

				bezier = myBezier, 0.05, 0.9, 0.1, 1.05

				animation = windows, 1, 7, myBezier
				animation = windowsOut, 1, 7, default, popin 80%
				animation = border, 1, 10, default
				animation = borderangle, 1, 8, default
				animation = fade, 1, 7, default
				animation = workspaces, 1, 6, default
		}

		dwindle {
		# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
			pseudotile = yes # master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
				preserve_split = yes # you probably want this
		}

		gestures {
		# See https://wiki.hyprland.org/Configuring/Variables/ for more
		}

		misc {
		# See https://wiki.hyprland.org/Configuring/Variables/ for more
			force_default_wallpaper = 0
			vfr = true
			vrr = 1
			disable_hyprland_logo = true
			disable_splash_rendering = true
			mouse_move_enables_dpms = true
			key_press_enables_dpms = true
			background_color = 0x${bg}
			enable_swallow = true
			swallow_regex = ^(kitty)$
		}


		# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more

		# See https://wiki.hyprland.org/Configuring/Keywords/ for more
		$mainMod = SUPER

		# Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
		bind = $mainMod, Return, exec, kitty
		bind = $mainMod, Q, killactive
		bind = SUPERSHIFT, SPACE, togglefloating
		bind = $mainMod, D, exec, pkill rofi || rofi -show drun -theme ~/.config/rofi/launcher.rasi
		bind = $mainMod, P, pseudo # dwindle
		bind = $mainMod, J, togglesplit # dwindle
		bind=SUPERSHIFT,R,exec,${pkgs.hyprland}/bin/hyprctl reload
		bind=SUPER,F,fullscreen
		bind=SUPER,L,exec,~/Scripts/swaylock.sh
		bind=SUPER,N,exec,${pkgs.swaynotificationcenter}/bin/swaync-client -t
		bind = SUPERSHIFT, E,exec, pkill rofi || .config/rofi/powermenu.sh
        	bind=,print,exec,${pkgs.grimblast}/bin/grimblast --notify --freeze --wait 1 copysave area ~/Pictures/$(date +%Y-%m-%dT%H%M%S).png
		bind=SUPER,Y,exec,pkill rofi || cliphist list | rofi -dmenu -theme $HOME/.config/rofi/clipboard.rasi | cliphist decode | wl-copy
		bind=SUPER,T,exec,pkill rofi || ~/Scripts/waybar-tmux-manager.sh
		bind=SUPER,code:49,exec,pypr toggle term
		bind=SUPER,Z,exec, pypr zoom
		bind=SUPER,E,exec,pypr toggle files
		bind=SUPER,I,exec,~/Scripts/imv_launcher.sh
		bind=SUPERSHIFT,T,exec,pkill rofi || ~/Scripts/theme-rofi.sh

        	binde=,XF86AudioLowerVolume,exec,${pkgs.pulseaudio}/bin/pactl set-sink-volume @DEFAULT_SINK@ -5%
        	binde=,XF86AudioRaiseVolume,exec,${pkgs.pulseaudio}/bin/pactl set-sink-volume @DEFAULT_SINK@ +5%
         	bind=,XF86AudioMute,exec,${pkgs.pulseaudio}/bin/pactl set-sink-mute @DEFAULT_SINK@ toggle

        	bind=,XF86AudioMicMute,exec,${pkgs.pulseaudio}/bin/pactl set-source-mute @DEFAULT_SOURCE@ 1

		# Media playback
		bind=,XF86AudioPlay,exec,${pkgs.playerctl}/bin/playerctl play-pause
		bind=,XF86AudioNext,exec,${pkgs.playerctl}/bin/playerctl next
		bind=,XF86AudioPrev,exec,${pkgs.playerctl}/bin/playerctl previous
		bind=,XF86AudioStop,exec,${pkgs.playerctl}/bin/playerctl stop

		# Brightness
		binde=,XF86MonBrightnessUp,exec,${pkgs.brightnessctl}/bin/brightnessctl set +5%
		binde=,XF86MonBrightnessDown,exec,${pkgs.brightnessctl}/bin/brightnessctl set 5%-

		# Scratchpads
		bind=SUPER,B,exec,pypr toggle systeminfo
		bind=SUPERSHIFT,B,exec,pypr toggle lazydocker
		bind=SUPER,A,exec,pypr toggle pavucontrol

		# Center floating window
		bind=SUPER,C,centerwindow

		# Pin floating window to all workspaces
		bind=SUPERSHIFT,P,pin

		# Move windows between monitors
		bind=SUPERALT,left,focusmonitor,-1
		bind=SUPERALT,right,focusmonitor,+1
		bind=SUPERALTSHIFT,left,movewindow,mon:-1
		bind=SUPERALTSHIFT,right,movewindow,mon:+1

		# Alt-tab window cycling
		bind=ALT,Tab,cyclenext
		bind=ALTSHIFT,Tab,cyclenext,prev

		# Window grouping (tabs)
		bind=SUPER,G,togglegroup
		bind=SUPERSHIFT,G,lockactivegroup,toggle
		bind=SUPER,Tab,changegroupactive,f
		bind=SUPERSHIFT,Tab,changegroupactive,b

		# Move focus with mainMod + arrow keys
		bind = $mainMod, left, movefocus, l
		bind = $mainMod, right, movefocus, r
		bind = $mainMod, up, movefocus, u
		bind = $mainMod, down, movefocus, d

		# Move active window + arrowkeys
		bind = SUPERSHIFT,left,movewindow, l
		bind = SUPERSHIFT,right,movewindow, r
		bind = SUPERSHIFT,up,movewindow, u
		bind = SUPERSHIFT,down,movewindow, d

		# Switch workspaces with mainMod + [0-9]
		bind = $mainMod, 1, workspace, 1
		bind = $mainMod, 2, workspace, 2
		bind = $mainMod, 3, workspace, 3
		bind = $mainMod, 4, workspace, 4
		bind = $mainMod, 5, workspace, 5
		bind = $mainMod, 6, workspace, 6
		bind = $mainMod, 7, workspace, 7
		bind = $mainMod, 8, workspace, 8
		bind = $mainMod, 9, workspace, 9
		bind = $mainMod, 0, workspace, 10

		# Move active window to a workspace with mainMod + SHIFT + [0-9]
		bind = $mainMod SHIFT, 1, movetoworkspace, 1
		bind = $mainMod SHIFT, 2, movetoworkspace, 2
		bind = $mainMod SHIFT, 3, movetoworkspace, 3
		bind = $mainMod SHIFT, 4, movetoworkspace, 4
		bind = $mainMod SHIFT, 5, movetoworkspace, 5
		bind = $mainMod SHIFT, 6, movetoworkspace, 6
		bind = $mainMod SHIFT, 7, movetoworkspace, 7
		bind = $mainMod SHIFT, 8, movetoworkspace, 8
		bind = $mainMod SHIFT, 9, movetoworkspace, 9
		bind = $mainMod SHIFT, 0, movetoworkspace, 10

		# Example special workspace (scratchpad)
		bind = $mainMod, S, togglespecialworkspace, magic
		bind = $mainMod SHIFT, S, movetoworkspace, special:magic

		# Scroll through existing workspaces with mainMod + scroll
		bind = $mainMod, mouse_down, workspace, e+1
		bind = $mainMod, mouse_up, workspace, e-1

		# Move/resize windows with mainMod + LMB/RMB and dragging
		bindm = $mainMod, mouse:272, movewindow
		bindm = $mainMod, mouse:273, resizewindow

		bind = SUPER,R,submap,resize
		submap=resize
		binde =,right,resizeactive,20 0
		binde =,left,resizeactive,-20 0
		binde =,up,resizeactive,0 -20
		binde =,down,resizeactive,0 20
		bind=,escape,submap,reset
		submap=reset

		# Float common dialogs and popups
		windowrule = float on, match:title ^(Open File)(.*)$
		windowrule = float on, match:title ^(Open Folder)(.*)$
		windowrule = float on, match:title ^(Select a File)(.*)$
		windowrule = float on, match:title ^(Save As)(.*)$
		windowrule = float on, match:title ^(Save File)(.*)$
		windowrule = float on, match:title ^(File Upload)(.*)$
		windowrule = float on, match:title ^(Confirm)(.*)$
		windowrule = float on, match:title ^(Authentication)(.*)$
		windowrule = float on, match:title ^(Preferences)$
		windowrule = float on, match:title ^(Properties)$
		windowrule = float on, match:title ^(About )(.*)$
		windowrule = float on, match:title ^(Print)(.*)$
		windowrule = float on, match:title ^(Color Picker)(.*)$
		windowrule = float on, match:title ^(Sign in)(.*)$
		windowrule = float on, match:title ^(Settings)(.*)$
		windowrule = float on, match:title ^(Options)(.*)$
		windowrule = float on, match:title ^(Warning)(.*)$
		windowrule = float on, match:title ^(Error)(.*)$
		windowrule = float on, match:title ^(Progress)(.*)$
		windowrule = float on, match:title ^(Export)(.*)$
		windowrule = float on, match:title ^(Import)(.*)$
		windowrule = float on, match:title ^(Update)(.*)$
		windowrule = float on, match:title ^(Download)(.*)$

		# Float common popup app classes
		windowrule = float on, match:class ^(xdg-desktop-portal)(.*)$
		windowrule = float on, match:class ^(polkit)(.*)$
		windowrule = float on, match:class ^(zenity)(.*)$
		windowrule = float on, match:class ^(nm-connection-editor)$
		windowrule = float on, match:class ^(blueman)(.*)$
		windowrule = float on, match:class ^(font-manager)$

		# Steam
		windowrule = float on, match:title ^(Steam)$
		windowrule = float on, match:title ^(Friends List)$

		# Insync
		windowrule = float on, match:title ^(Insync)(.*)$

		# Scratchpad
		windowrule {
			name = scratchpad
			match:class = ^(scratchpad)$
			float = on
			center = on
			workspace = special silent
		}

		# Pavucontrol
		windowrule {
			name = pavucontrol
			match:class = ^(org\.pulseaudio\.pavucontrol|pavucontrol)$
			float = on
			size = 50% 40%
			center = on
			opacity = 0.80
		}

		# Thunar
		windowrule {
			name = thunar
			match:class = ^(thunar)$
			float = on
			opacity = 0.90
		}

		# Imv
		windowrule {
			name = imv
			match:class = ^(imv)$
			float = on
			size = 70% 70%
			center = on
		}

		# Layer rules for blur
		layerrule {
			name = blur-layers
			match:namespace = ^(rofi|waybar|swaync)$
			blur = on
			ignore_alpha = 0.5
		}

		# Opacity for certain apps
		windowrule = opacity 0.9 0.9, match:class ^(Slack|WebCord|Spotify|Kitty)$

		# Initialize theme files from Nix defaults before apps start
		exec-once = [ ! -f $HOME/.config/waybar/style.css ] && cp $HOME/.config/waybar/style.default.css $HOME/.config/waybar/style.css && chmod u+w $HOME/.config/waybar/style.css; [ ! -f $HOME/.config/rofi/shared/colors.rasi ] && cp $HOME/.config/rofi/shared/colors.default.rasi $HOME/.config/rofi/shared/colors.rasi && chmod u+w $HOME/.config/rofi/shared/colors.rasi; [ ! -f $HOME/.config/swaync/style.css ] && cp $HOME/.config/swaync/style.default.css $HOME/.config/swaync/style.css && chmod u+w $HOME/.config/swaync/style.css; true

		exec-once=${pkgs.swww}/bin/swww-daemon
		exec-once=${pkgs.waybar}/bin/waybar
		exec-once=${pkgs.swaynotificationcenter}/bin/swaync
		exec-once=${pkgs.openrazer-daemon}/bin/openrazer-daemon
		exec-once=${pkgs.networkmanagerapplet}/bin/nm-applet --indicator
		exec-once=${pkgs.hyprland-autoname-workspaces}/bin/hyprland-autoname-workspaces
		exec-once=pypr
		exec-once = wl-clipboard-history -t
		exec-once = wl-paste --watch cliphist store
		exec-once = rm "$HOME/.cache/cliphist/db"   #it'll delete history at every restart
		exec-once = sleep 3 && ~/Scripts/swww_random.sh ~/Pictures/Wallpapers/
		exec-once = sleep 4 && insync start --qt-qpa-platform=xcb --no-daemon
		# Restore saved theme if one was selected
		exec-once = sleep 2 && test -f $HOME/.config/theme/current && ~/Scripts/theme-switcher.sh $HOME/.config/theme/themes/$(cat $HOME/.config/theme/current).json
		${execute}
		'';
	in
	{
		xdg.configFile."hypr/hyprland.conf".text = hyprlandConf;

	};
}
